resolver: lts-14.27

packages:
- hw0
- hw1
- hw2
- hw3
- hw4
- practice1

extra-deps:
  - tasty-hspec-1.1.5.1
  - hspec-hedgehog-0.0.1.1
  - split-0.2.3.4
  - validity-0.8.0.0
  - filepath-1.4.2.1
  - time-1.8.0.2

flags: {}

extra-package-dbs: []
